name: Deryck Lio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6039426
author:
  name: Deryck Lio
  email: d@derycklio.com
  url: 'http://www.derycklio.com'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Deryck Lio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030102'
    - '#FBF8E8'
    - '#9E664B'
    - '#DBA580'
    - '#3C401D'
  brandStrength: 1
  lightness: 0.9798568501137197
  saturation: 0.6525228160899132
  rhythmicContrast: 0.05366360861808062
purpose: []
